# -*- coding: utf-8 -*-
"""Telus_Task2.ipynb

Automatically generated by Colaboratory.

Author: dipanjan chatterjee
"""

#!pip install fuzzywuzzy

import pandas as pd
from fuzzywuzzy import process 
import csv
import sys
from datetime import datetime


#This method is the fuzzywuzzy matcher which takes the dataframe and each word and returns the company_name of most commonly matched word
def fuzzywuzzy_matcher(df_dic,word):
  company_name = ''
  score = process.extractOne(word,df_dic)
  if (len(score[0].split(' '))>10):
    company_name = score[2]
  else:
    company_name = score[0]
  return company_name

#This is the driver function that takes the list of words and the filepath generated by the Task1 by the user
def driver(wordlist,file):
  #print (type(file))
  df = pd.read_csv(file)
  df_dic = {}
  resultant_dict = {'word':'Standard Name'}
  temp_dic = {}
  for index, row in df.iterrows():
    df_dic[row[0]]=row[1]
  for word in wordlist:
    company_name = fuzzywuzzy_matcher(df_dic,word)
    temp_dic[word] = company_name
    resultant_dict.update(temp_dic)
  
  filename = datetime.now().strftime('Task2_Output-%Y-%m-%d-%H-%M-%S.csv')
  path = open(filename, "w")
  z = csv.writer(path)
  for k,v in resultant_dict.items():
    z.writerow([k,v])
  path.close()





if __name__=='__main__':
	filename = sys.argv[1]
	wordlist = sys.argv[2]
	formatted_word_list = list(map(str, wordlist.strip('[]').split(',')))
	#filename = "/content/Canadian_Company_Details.csv"
	driver(formatted_word_list,filename)

